/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brickgame;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Dell
 */
public class giff extends javax.swing.JFrame {

    /**
     * Creates new form giff
     */
    public giff()
    {
        initComponents();
        setVisible(true);
        setBounds(200,90,1000,500);
        
       // setUndecorated(true);
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // JLabel lbb = new JLabel("");
       // ImageIcon iconn = new ImageIcon(this.getClass().getResource("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Brickgame\\src\\brickgame\\img\\gif.gif"));
        lbb1.setIcon(new ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\Brickgame\\src\\brickgame\\gif.gif"));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JProgressBar();
        txt = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        bar.setBackground(new java.awt.Color(0, 255, 0));
        bar.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(bar);
        bar.setBounds(50, 440, 910, 20);

        txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 0));
        txt.setText("Please Wait.......");
        getContentPane().add(txt);
        txt.setBounds(50, 420, 340, 20);

        num.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 36)); // NOI18N
        num.setForeground(new java.awt.Color(255, 255, 0));
        num.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        num.setText("99");
        getContentPane().add(num);
        num.setBounds(430, 380, 140, 70);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickgame/Image/zexit1  (2).png"))); // NOI18N
        b1.setText(" ");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                b1MouseReleased(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(920, 10, 50, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickgame/Image/zlogo6.png"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 360, 90, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickgame/Image/zlogo4.png"))); // NOI18N
        jLabel3.setText(" ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 390, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickgame/Image/zlogo3.png"))); // NOI18N
        jLabel2.setText("jLabel2 ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 20, 810, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickgame/Image/zlogo2.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(810, 370, 180, 70);

        lbb1.setBackground(new java.awt.Color(0, 0, 0));
        lbb1.setText(" ");
        getContentPane().add(lbb1);
        lbb1.setBounds(0, 0, 1030, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickgame/Image/zexit1  (1).png")));
    }//GEN-LAST:event_b1MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
        // TODO add your handling code here:
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brickgame/Image/zexit1  (2).png")));
    }//GEN-LAST:event_b1MouseExited

    private void b1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseReleased
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_b1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new giff().setVisible(true);
            }
        });
        
        //audioclass ac2 = new audioclass();
            //ac2.wc1.play();
        giff Splash = new giff();
        Splash.setVisible(true);
        
        try
        {
            int i;
              for( i=0; i<=10; i++)
            {
                Thread.sleep(80);
               audioclass ac2 = new audioclass();
            ac2.wc1.play();
            }
            
            audioclass ac1 = new audioclass();
                ac1.wait1.play();
            //int i;
            for( i=10; i<=30; i++)
            {
               
                Thread.sleep(80);
               Splash.txt.setText("please wait.............."); 
               Splash.num.setText(Integer.toString(i)+ "%");
               Splash.bar.setValue(i);
             
            
            }
           
            Thread.sleep(900);
             audioclass ac = new audioclass();
             ac.devlp1.play();
            for( i=30; i<=70; i++)
            {
             
               
                
                
                Thread.sleep(80);
               Splash.txt.setText("THIS GAME DEVELOPED BY PRAMOD......"); 
               Splash.num.setText(Integer.toString(i)+ "%");
               Splash.bar.setValue(i);
             
            
            }
            
           Thread.sleep(900);
           audioclass ac3 = new audioclass();
             ac3.load1.play();
            for( i=70; i<=100; i++)
            {
                              
                Thread.sleep(80);
               Splash.txt.setText("Loading game................."); 
               Splash.num.setText(Integer.toString(i)+ "%");
               Splash.bar.setValue(i);
               //Thread.sleep(600);
                  if(i == 100)
            {
                  Thread.sleep(1300);
               Splash.dispose();
                new OPTION().setVisible(true);
                   System.out.println("successfully work");
            }
            else
            {
            System.out.println("sorry login again");
            
            }
            }
            // Thread.sleep(1000);
            
        }catch(Exception e){ }
        
        
        
        
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbb1;
    private javax.swing.JLabel num;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
